version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app-base
    volumes:
      - ./:/app
    container_name: app-base
    ports:
      - 8889:8080
